# Generated by Django 3.1.7 on 2021-04-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='stock_owned',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
