# Generated by Django 3.1.7 on 2021-04-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_userprofileinfo_stock_owned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='stock_owned',
        ),
        migrations.AlterField(
            model_name='stocks',
            name='prevclose',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
