# Generated by Django 3.1.7 on 2021-04-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20210412_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='Last',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='high',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='low',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='open',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
