# Generated by Django 3.1.7 on 2021-04-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_auto_20210412_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='Last',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='open',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='prevclose',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
