# Generated by Django 3.1.7 on 2021-04-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0011_userprofileinfo_stock1'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=50)),
                ('industry', models.CharField(max_length=50)),
                ('stocksymbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.stocks')),
            ],
        ),
    ]
