# Generated by Django 3.1.7 on 2021-04-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_stocks_no_of_trades_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='shares_count',
            field=models.IntegerField(default=50),
        ),
    ]
